const topics = [
  "How do I change my avatar?",
  "How do I change my email?",
  "How do I change my email preferences?",
  "How do I change my first or last name?",
  "How do I change my password?",
  "How do I log out of my current session?",
  "How do I view my monthly availability?",
  "How do I view my monthly A/P form responses?",
  "How do I view an A/P form?",
  "How do I add my availability to an A/P form?",
  "How do I update my A/P form availability?",
  "How do I view my monthly schedule?",
  "How is scheduling determined?"
];

export const stafftopics = [
  ...topics,
  "How do I get started?",
  "How do I create an event?",
  "How do I delete an event?",
  "How do I edit an event?",
  "How do I resend an event's email reminders?",
  "How do I schedule or assign employees to an event?",
  "How do I view all events?",
  "How do I create an A/P form?",
  "How do I delete an A/P form?",
  "How do I edit an A/P form?",
  "How do I resend an A/P form reminders?",
  "How do I send out monthly A/P form emails?",
  "How do I view all forms?",
  "How do I create an email?",
  "How do I delete an email?",
  "How do I edit an email?",
  "How do I resend an email?",
  "How do I view all emails?",
  "How do I create a member?",
  "How I delete a member?",
  "How I edit, update, or suspend a member?",
  "How do I view all members?",
  "How do I edit or resend member authorization?",
  "How do I view a member's profile, availability, responses or schedule?",
  "How do I view all members' availability for the current month's A/P form?",
  "How do I view all members' authorizations?",
  "How do I create monthly schedules?",
  "How do I view the monthly schedule?",
  "How do I view a member's monthly schedule?",
  "How do I create a season?",
  "How do I delete a season?",
  "How do I edit a season?",
  "How do I view all seasons?",
  "How do the automated services work?"
];

export default topics;
