// SIDEMENU
export const SIDEMENU_EXPANDED_TABS = "SIDEMENU/EXPANDED_TABS";
export const SIDEMENU_SELECTED_TABS = "SIDEMENU/SELECTED_TABS";

// SERVER
export const SERVER_RESET_MESSAGE = "SERVER/RESET_MESSAGE";
export const SERVER_ERROR_MESSAGE = "SERVER/ERROR_MESSAGE";
export const SERVER_MESSAGE = "SERVER/MESSAGE";

// USER
// user avatar
export const USER_DELETE_AVATAR = "USER/DELETE_AVATAR";
export const USER_UPDATE_AVATAR = "USER/UPDATE_AVATAR";
export const USER_SET_AVATAR = "USER/SET_AVATAR";
// user password
export const USER_PASSWORD_UPDATE = "USER/PASSWORD_UPDATE";
export const USER_PASSWORD_RESET = "USER/PASSWORD_RESET";
// ui sidebar state
export const USER_SET_SIDEBAR_STATE = "USER/SET_SIDEBAR_STATE";
// user auth
export const USER_CHECK_SESSION = "USER/CHECK_SESSION";
export const USER_SET_SESSION = "USER/SET_SESSION";
export const USER_SIGNIN_ATTEMPT = "USER/SIGNIN_ATTEMPT";
export const USER_REMOVE_SESSION = "USER/REMOVE_SESSION";
export const USER_SIGNOUT_SESSION = "USER/SIGNOUT_SESSION";
export const USER_SIGNUP = "USER/SIGNUP";
export const USER_UPDATE_SESSION = "USER/UPDATE_SESSION";
